services:
  - type: web
    name: image-link-card
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: BASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
